export const Messages = {
    MSG_TOO_MANY_REQUESTS: "Too many requests. Please try again later.",
    MSG_LIST: "List Found.",
    MSG_NO_ID: "ID Not Exists.",
    MSG_DATA: "Data Found.",
    MSG_NO_RECORD: "No Record Found.",
    MSG_SAVED: "Information Saved Successfully.",
    MSG_UPDATED: "Information Updated Successfully.",
    MSG_NOT_UPDATED: "Information Does not Updated Successfully.",
    MSG_ALREADY_UPDATED: "Information Already Updated.",
    MSG_INVALID_DATA: "Invalid Data.",
    MSG_SUCCESS: "Information saved successfully.",
    MSG_UPDATE_SUCCESS: "Information updated successfully.",
    MSG_INVALID_ID: "Invalid Id.",
    MSG_DATA_FOUND: "Data Found.",
    MSG_CODE_GENERATED_SUCCESSFULLY: "Code generated successfully.",
    MSG_CODE_MATCHED_SUCCESSFULLY: "Code matched successfully",
    MSG_EXPIRED_CODE: "Code Expired.",
    MSG_USER_INACTIVE: "User Inactive, Code generated successfully.",
    MSG_EXPIRED_CODE_AND_NEW_GENERATED: "The code expired. New code generated successfully.",
    MSG_INVALID_CODE: "Invalid Code.",
    MSG_DELETE_SUCCESS: "Information deleted successfully.", 
    MSG_INVALID_REQUEST: "Invalid Request.",
    MSG_INVALID_OLD_PASSWORD: "Old password does not match",
    MSG_INVALID_PASSWORD: "Password does not match",
    MSG_UPDATE_PASSWORD_SUCCESS: "Password Updated Successfully",
    MSG_INVALID_EMAIL: "Invalid Email",
    MSG_CHECK_EMAIL: "Check your Email",
    MSG_EMAIL_EXIST: "Email already exists.",
    MSG_EMAIL_REQUIRED: "Email is required.",
    MSG_ALREADY_EXIST: "Already exists.",
    MSG_COMPANY_COUNTRY_ALREADY_EXIST: "Company Name in this Country Already exists.",
    MSG_USER_ROLE_ALREADY_EXIST: "User Role Already exists.",
    MSG_INVALID_CRED: "Invalid credentials.",
    MSG_EMAIL_NOT_VALID: "Email not confirmed yet.",
    MSG_EMAIL_NOT_EXIST: "Email does not exist.",
    MSG_PHONE_NOT_EXIST: "Phone does not exist.",
    MSG_PHONE_EXIST: "Phone number exist.",
    MSG_CODE_NOT_EXIST: "Code does not exist.",
    MSG_TEMP_ACCOUNT_BLOCKED: "Your account has been temporarily locked for 2 hours due to multiple unsuccessful login attempts. Please try again later or contact support for assistance.",
    MSG_EMAIL_NOT_FOUND_OR_USER_DELETED: "Email not found or user deleted.",
    MSG_LOGIN_SUCCESS: "Login successful.",
    MSG_LOGOUT_SUCCESS: "Logout successful.",
    MSG_LOGIN_FAILED: "Login unsuccessful.",
    MSG_DELETE_ROLE_FAILED: "Delete role unsuccessful.",
    MSG_LOGOUT_FAILED: "Logout unsuccessful.",
    MSG_PASSWORD_LENGTH: "Password Length must be greater than 7.",
    MSG_DB_CONNECTION_SUCCESS: "Database Connection Successful",
    MSG_DB_CONNECTION_ERROR: "Database Connection Error",
    MSG_UNEXPECTED_ERROR: "An unexpected error occurred.",
    MSG_NOT_VERIFIED: "User Is not verified",
    MSG_USER_NOT_EXIST: "User not Exist",
    MSG_INVALID_NUMBER: "Invalid Phone Number",
    MSG_TOKEN_REQUIRED: "A token is required for authentication",
    MSG_TOKEN_INVALID: "Token Invalid",
    MSG_TOKEN_NOT_EXIST: "Token does not Exist",
    MSG_TOKEN_CLEAR: "Token Clear Successfully",
    MSG_INTERNAL_SERVER_ERROR: "Internal Server Error",
    MSG_USER_ALREADY_VERIFIED:"User Already Verified",
    MSG_CORPORATE_NOT_VERIFIEF:"Corporate not Verified",
    MSG_CORPORATE_DEACTIVE:"Corporate deactive",
    MSG_USER_NO_MOBILE_APP_ACCESS:"No Mobile App Access",
    MSG_FAILED_AUTH_TOKEN:"Failed to Authenticate Token.",
    MSG_DUPLICATE_ENTRY:"The email or phone number already exists. Please use a unique email and phone number.",
    MSG_DUPLICATE_PHONE:"This phone number already exists. Please use a unique phone number.",
    MSG_CUSTOMER_DELETED:"Customer deleted successfully",
    MSG_SUPPLIER_DELETED:"Supplier deleted successfully",
    MSG_USER_IS_NOT_AUTHORIZED:"User is not authorized",
    MSG_SOME_ERROR_OCCURED: "some error occured",
    MSG_ENV_DATA_NOT_FOUND: ".env data not found",
    MSG_USER_EXIST_IN_MORE_THEN_ONE_COMPANY: "user exist in more then one company",
    MSG_PLEASE_CONTACT_YOUR_COMPANY: "Please contact your company",
    MSG_EMAIL_PASSWORD_REQUIRED:"Email and password are required",
    MSG_MULTIPLE_EXISTANCE:"Role Exist already",
    MSG_NEW_PASSWORD_REQUIRE:'New password is required',
    MSG_FAILED_PASSWORD:'Failed to update password',
    MSG_SERVER_ERROR:'Server Error',
    MSG_USER_DEACTIVATED:'User account is deactivated. Please contact support for assistance.',
    MSG_INVALID_CLIENT_SECRET_OR_CLIENT_ID : "Invalid client secret or client id",
    MSG_ROLE_NOT_EXIST:'Role does not exist',
    MSG_ROLE_ASSIGN:'Please Un Assign Role First',
    MSG_REQUEST_NOT_PERMITED_ROLE_IS_ASSIGNED_TO_USER : "Request not permited as role is already assigned to a user",
    MSG_SOME_ROLE_DELETE_FAILED: "some role delete request failed",
    MSG_INVALID_T_PIN:"T Pin does not match",
    MSG_EMAIL_COOLDOWN:"Too many requests. Please try again later.",
    MSG_PORTAL_MISMATCH:"These credentials are not valid for this portal.",
    MSG_TOKEN_EXPIRED:"Session expired. Please log in again.",
    MSG_ADMIN_NOT_EXIST:"Admin does not exist.",
    MSG_MERCHANT_NOT_EXIST:"Merchant does not exist.",
    MSG_ACCOUNT_NOT_LOCKED:"This account is not locked.",
    MSG_ACCOUNT_UNLOCKED:"Account unlocked successfully.",
    MSG_OTP_INVALID_OR_EXPIRED:"Invalid or expired OTP.",
    MSG_OTP_SENT:"An OTP has been sent to your email.",
    MSG_ACCOUNT_LOCKED_CANNOT_RESET:"This account is locked. Contact your administrator to unlock it before resetting your password.",
    MSG_PASSWORD_RESET_SUCCESS:"Password has been reset successfully.",
    MSG_SUPER_ADMIN_EXISTS:"A Super Admin account already exists.",
    MSG_DEPARTMENT_NOT_EXIST:"Department does not exist.",
    MSG_DESIGNATION_NOT_EXIST:"Designation does not exist.",
    MSG_JOB_POSITIONS_FILLED:"All open positions for this job have already been filled.",
    MSG_EMPLOYEE_NOT_EXIST:"Employee does not exist.",
    MSG_INVALID_HOD:"Selected Head of Department must be an existing, active employee.",
    MSG_INVALID_WEEKLY_SCHEDULE:"At least one working day is required, and each working day's start time must be before its end time.",
    MSG_INVALID_LOAN_STATUS:"This action is not valid for the loan's current status.",
    MSG_INSTALLMENT_NOT_EXIST:"Installment not found.",
    MSG_INSTALLMENT_ALREADY_PAID:"This installment has already been paid.",
    MSG_INVALID_EXPENSE_STATUS:"This action is not valid for the expense's current status.",
    MSG_EXPENSE_ALREADY_REIMBURSED:"This expense has already been reimbursed.",
    MSG_PF_POLICY_NOT_EXIST:"No Provident Fund policy has been set up for this tenant yet.",
    MSG_PF_DUPLICATE_CONTRIBUTION:"A contribution for this employee and month already exists.",
    MSG_PF_NO_CURRENT_SALARY:"This employee has no current salary record to compute the contribution from.",
    MSG_PF_ACCOUNT_NOT_EXIST:"Provident Fund account not found for this employee.",
    MSG_PF_INSUFFICIENT_BALANCE:"The requested withdrawal amount exceeds the available Provident Fund balance.",
    MSG_INVALID_PF_WITHDRAWAL_STATUS:"This action is not valid for the withdrawal's current status.",
    MSG_POLICY_IS_HISTORICAL:"This policy has been superseded and can no longer be edited.",
    MSG_LEAVE_TYPE_NOT_EXIST:"Leave type does not exist or is inactive.",
    MSG_LEAVE_GENDER_NOT_APPLICABLE:"This leave type does not apply to this employee.",
    MSG_LEAVE_OVERLAP:"This employee already has a pending or approved leave overlapping these dates.",
    MSG_LEAVE_INSUFFICIENT_BALANCE:"Requested days exceed the employee's remaining balance for this leave type.",
    MSG_INVALID_LEAVE_STATUS:"This action is not valid for the leave request's current status.",
    MSG_INVALID_PAYROLL_STATUS:"This action is not valid for the payroll run's current status.",
    MSG_INVALID_SPECIAL_PAYMENT_STATUS:"This action is not valid for the special payment's current status.",
    MSG_INVALID_SPECIAL_PAYMENT_TYPE:"Special payment type does not exist.",
    MSG_NO_ELIGIBLE_EMPLOYEES:"No eligible employees were found for this target.",
    MSG_INVALID_REQUEST_STATUS:"This action is not valid for the request's current status.",
    MSG_INVALID_REQUEST_TYPE:"Unknown request type.",
    MSG_ACTIVE_EXIT_EXISTS:"This employee already has an active exit in progress.",
    MSG_INVALID_EXIT_STATUS:"This action is not valid for the exit's current status.",
    MSG_ACCOUNT_CODE_EXISTS:"An account with this code already exists.",
    MSG_ACCOUNT_NOT_EXIST:"Chart of Account entry not found.",
    MSG_JOURNAL_NOT_BALANCED:"Journal entry is not balanced: total debit must equal total credit.",
    MSG_JOURNAL_ENTRY_NOT_EXIST:"Journal entry not found.",
    MSG_BANK_ACCOUNT_NOT_EXIST:"Bank/cash account not found.",
    MSG_VENDOR_BILL_NOT_EXIST:"Vendor bill not found.",
    MSG_INVALID_BILL_STATUS:"This action is not valid for the bill's current status.",
    MSG_CUSTOMER_INVOICE_NOT_EXIST:"Customer invoice not found.",
    MSG_INVALID_INVOICE_STATUS:"This action is not valid for the invoice's current status.",
    MSG_RECONCILIATION_SESSION_NOT_EXIST:"Reconciliation session not found.",
    MSG_INVALID_RECONCILIATION_STATUS:"This session has already been reconciled.",
    MSG_PAYMENT_EXCEEDS_BALANCE:"Payment amount exceeds the outstanding balance due.",
    MSG_REFUND_EXCEEDS_DUE:"Refund amount exceeds what is actually owed back to the customer.",
    MSG_INVALID_THEME_COLOR:"Theme color must be a valid hex color (e.g. #3643AB).",
    MSG_PAYMENT_NOT_EXIST:"Payment not found.",

    // Inventory / Warehouse / Client & Vendor
    MSG_CATEGORY_NOT_EXIST:"Category not found.",
    MSG_PRODUCT_NOT_EXIST:"Product not found.",
    MSG_VARIANT_NOT_EXIST:"Variant not found.",
    MSG_SKU_EXISTS:"A variant with this SKU already exists.",
    MSG_PRODUCTION_ORDER_NOT_EXIST:"Production order not found.",
    MSG_INVALID_PRODUCTION_STATUS:"This action is not valid for the production order's current status.",
    MSG_PRODUCTION_OUTPUT_CONSUMED:"This production cannot be reversed because some of the finished quantity has already been sold or used.",
    MSG_WAREHOUSE_NOT_EXIST:"Warehouse not found.",
    MSG_WAREHOUSE_HAS_STOCK:"This warehouse still holds stock and cannot be deleted.",
    MSG_INSUFFICIENT_STOCK:"Insufficient stock available for this action.",
    MSG_STOCK_TRANSFER_NOT_EXIST:"Stock transfer not found.",
    MSG_INVALID_TRANSFER_STATUS:"This action is not valid for the transfer's current status.",
    MSG_TRANSFER_SAME_WAREHOUSE:"Source and destination warehouse cannot be the same.",
    MSG_TRANSFER_WAREHOUSE_NOT_FOUND:"Source or destination warehouse not found.",
    MSG_STOCK_ISSUE_NOT_EXIST:"Stock issue not found.",
    MSG_STOCK_ISSUE_WAREHOUSE_NOT_FOUND:"Warehouse not found.",
    MSG_PRODUCTION_WAREHOUSE_NOT_FOUND:"Warehouse not found.",
    MSG_PRODUCTION_VARIANT_NOT_FOUND:"One or more products in this production order were not found.",
    MSG_QUARANTINE_LOT_NOT_EXIST:"Not-for-sale lot not found.",
    MSG_QUARANTINE_INSUFFICIENT:"Not enough not-for-sale quantity remains on this lot.",
    MSG_QUARANTINE_WAREHOUSE_MISMATCH:"Production warehouse must match the not-for-sale lot warehouse.",
    MSG_CUSTOMER_NOT_EXIST:"Customer not found.",
    MSG_CUSTOMER_OPENING_BALANCE_LOCKED:"Opening balance cannot be changed after a sale invoice has been created for this customer.",
    MSG_SUPPLIER_NOT_EXIST:"Supplier not found.",
    MSG_SALE_INVOICE_NOT_EXIST:"Sale invoice not found.",
    MSG_INVALID_DELIVERY_STATUS:"This action is not valid for the invoice's current delivery status.",
    MSG_QUOTATION_NOT_EXIST:"Quotation not found.",
    MSG_INVALID_QUOTATION_STATUS:"This action is not valid for the quotation's current status.",
    MSG_QUOTATION_ALREADY_CONVERTED:"This quotation has already been converted to an invoice.",
    MSG_CREDIT_NOTE_NOT_EXIST:"Credit note not found.",
    MSG_INVALID_CREDIT_NOTE_STATUS:"This action is not valid for the credit note's current status.",
    MSG_CREDIT_NOTE_INVOICE_NOT_FOUND:"The original invoice for this credit note was not found.",
    MSG_CREDIT_NOTE_CUSTOMER_MISMATCH:"The original invoice does not belong to the selected customer.",
    MSG_CREDIT_NOTE_EXCEEDS_INVOICE:"Credit note total exceeds the original invoice's remaining creditable amount.",
    MSG_PURCHASE_INVOICE_NOT_EXIST:"Purchase invoice not found.",
    MSG_INVALID_PURCHASE_STATUS:"This action is not valid for the purchase invoice's current status.",
    MSG_DEBIT_NOTE_NOT_EXIST:"Debit note not found.",
    MSG_INVALID_DEBIT_NOTE_STATUS:"This action is not valid for the debit note's current status.",
    MSG_DEBIT_NOTE_INVOICE_NOT_FOUND:"The original invoice for this debit note was not found.",
    MSG_DEBIT_NOTE_SUPPLIER_MISMATCH:"The original invoice does not belong to the selected supplier.",
    MSG_DEBIT_NOTE_EXCEEDS_INVOICE:"Debit note total exceeds the original invoice's remaining debitable amount.",
    MSG_SUPPLIER_REFUND_EXCEEDS_DUE:"Refund amount exceeds what the supplier actually owes back.",
    MSG_BUDGET_NOT_EXIST:"Budget entry not found.",
    MSG_BUDGET_INVALID_ACCOUNT_TYPE:"Budgets can only be set for Revenue or Expense accounts.",
    MSG_OPENING_STOCK_ALREADY_IMPORTED:"Opening stock has already been imported for this company. Ask a parent account to unlock it if another import is needed.",
    MSG_OPENING_STOCK_NOT_IMPORTED:"Opening stock has not been imported for this company.",
    MSG_OPENING_STOCK_IMPORT_INVALID:"Some opening-stock rows could not be imported. Fix the listed rows and try again.",
    MSG_OPENING_STOCK_UNLOCKED:"Opening stock import has been unlocked.",
    MSG_OPENING_STOCK_TENANT_REQUIRED:"Select an admin company or a merchant before importing opening stock.",
    MSG_OPENING_STOCK_IMPORTED:"Opening stock imported successfully.",

    // Asset Management
    MSG_ASSET_CATEGORY_NOT_EXIST:"Asset category not found.",
    MSG_ASSET_CATEGORY_CODE_EXISTS:"An asset category with this code already exists.",
    MSG_ASSET_CATEGORY_IN_USE:"This category still has assets assigned to it and cannot be deleted.",
    MSG_ASSET_NOT_EXIST:"Asset not found.",
    MSG_ASSET_ALREADY_DISPOSED:"This asset has already been disposed and can no longer be modified.",
    MSG_ASSET_NOT_ASSIGNED:"This asset is not currently assigned to anyone.",
    MSG_ASSET_ALREADY_ASSIGNED:"This asset is already assigned — return it before reassigning.",
    MSG_ASSET_REQUEST_NOT_EXIST:"Asset request not found.",
    MSG_INVALID_ASSET_REQUEST_STATUS:"This action is not valid for the request's current status.",
    MSG_ASSET_REQUEST_ALREADY_DECIDED:"This request has already been decided.",
    MSG_ASSET_AUDIT_NOT_EXIST:"Asset audit session not found.",
    MSG_ASSET_AUDIT_ALREADY_ACTIVE:"An audit session is already in progress — complete it before starting a new one.",
    MSG_ASSET_AUDIT_ALREADY_COMPLETED:"This audit session has already been completed.",
    MSG_ASSET_AUDIT_RESULT_NOT_FOUND:"This asset is not part of the active audit session.",

    // HR — Employee hierarchy integrity
    MSG_EMPLOYEE_MANAGER_CYCLE:"This manager assignment would create a reporting-chain cycle (an employee cannot, directly or indirectly, report to themselves).",
    MSG_DEPARTMENT_IN_USE:"This department still has active employees assigned to it and cannot be deleted.",
    MSG_DESIGNATION_IN_USE:"This designation still has active employees assigned to it and cannot be deleted.",
    MSG_LOAN_INVALID_AMOUNT:"Loan amount and number of installments must both be greater than zero.",
    MSG_EXPENSE_INVALID_AMOUNT:"Expense amount must be greater than zero.",
    MSG_SALARY_INVALID_AMOUNT:"Basic salary must be greater than zero.",
    MSG_SALARY_INVALID_EFFECTIVE_DATE:"The new effective date must be after the current salary record's own effective date.",
    MSG_POLICY_INVALID_IMPLEMENTED_DATE:"The new implemented date must be after the current policy's own implemented date.",
    MSG_SPECIAL_PAYMENT_INVALID_TARGET:"One or more selected employees were not found for this tenant.",
    MSG_LEAVE_INVALID_DAYS:"Leave days must be a positive number.",
    MSG_PAYROLL_DUPLICATE_RUN:"One or more selected employees already have a payroll run for this month that hasn't been cancelled.",
  };
  