import express from "express";
import userRoute from "./user/user-route";
import authRoute from "./auth/auth-route";
import adminRoute from "./admin/admin-route";
import merchantRoute from "./merchant/merchant-route";
import departmentRoute from "./department/department-route";
import designationRoute from "./designation/designation-route";
import employeeRoute from "./employee/employee-route";
import salaryRoute from "./salary/salary-route";
import loanRoute from "./loan/loan-route";
import expenseRoute from "./expense/expense-route";
import pfPolicyRoute from "./provident-fund/pf-policy-route";
import pfAccountRoute from "./provident-fund/pf-account-route";
import pfContributionRoute from "./provident-fund/pf-contribution-route";
import pfWithdrawalRoute from "./provident-fund/pf-withdrawal-route";
import attendancePolicyRoute from "./attendance/attendance-policy-route";
import attendanceRoute from "./attendance/attendance-route";
import leaveTypeRoute from "./leave/leave-type-route";
import leaveRoute from "./leave/leave-route";
import payrollRunRoute from "./payroll/payroll-run-route";
import specialPaymentTypeRoute from "./payroll/special-payment-type-route";
import specialPaymentRoute from "./payroll/special-payment-route";
import employeeRequestRoute from "./employee-request/employee-request-route";
import holidayRoute from "./holiday/holiday-route";
import announcementRoute from "./announcement/announcement-route";
import jobRoute from "./recruitment/job-route";
import candidateRoute from "./recruitment/candidate-route";
import onboardingTemplateRoute from "./onboarding/onboarding-template-route";
import onboardingRoute from "./onboarding/onboarding-route";
import offboardingRoute from "./offboarding/offboarding-route";
import chartOfAccountRoute from "./finance/chart-of-account-route";
import journalRoute from "./finance/journal-route";
import ledgerRoute from "./finance/ledger-route";
import reportsRoute from "./finance/reports-route";
import bankAccountRoute from "./finance/bank-account-route";
import vendorBillRoute from "./finance/vendor-bill-route";
import customerInvoiceRoute from "./finance/customer-invoice-route";
import paymentRoute from "./finance/payment-route";
import incomeEntryRoute from "./finance/income-entry-route";
import businessExpenseRoute from "./finance/business-expense-route";
import vatConfigRoute from "./finance/vat-config-route";
import bankStatementLineRoute from "./finance/bank-statement-line-route";
import reconciliationSessionRoute from "./finance/reconciliation-session-route";
import budgetRoute from "./finance/budget-route";
import assetCategoryRoute from "./asset/asset-category-route";
import assetRoute from "./asset/asset-route";
import assetRequestRoute from "./asset/asset-request-route";
import assetAuditRoute from "./asset/asset-audit-route";
import hrAnalyticsRoute from "./analytics/hr-analytics-route";
import inventoryAnalyticsRoute from "./analytics/inventory-analytics-route";
import salesAnalyticsRoute from "./analytics/sales-analytics-route";
import categoryRoute from "./inventory/category-route";
import productRoute from "./inventory/product-route";
import variantRoute from "./inventory/variant-route";
import productionRoute from "./inventory/production-route";
import stockBatchRoute from "./inventory/stock-batch-route";
import warehouseRoute from "./warehouse/warehouse-route";
import stockRoute from "./warehouse/stock-route";
import stockTransferRoute from "./warehouse/stock-transfer-route";
import stockIssueRoute from "./warehouse/stock-issue-route";
import customerRoute from "./sales/customer-route";
import geoRoute from "./reference/geo-route";
import saleInvoiceRoute from "./sales/sale-invoice-route";
import quotationRoute from "./sales/quotation-route";
import creditNoteRoute from "./sales/credit-note-route";
import supplierRoute from "./purchase/supplier-route";
import purchaseInvoiceRoute from "./purchase/purchase-invoice-route";
import debitNoteRoute from "./purchase/debit-note-route";
const router = express.Router();



router.use("/user", userRoute);
router.use("/auth", authRoute);
router.use("/admin", adminRoute);
router.use("/merchant", merchantRoute);
router.use("/department", departmentRoute);
router.use("/designation", designationRoute);
router.use("/employee", employeeRoute);
router.use("/salary", salaryRoute);
router.use("/loan", loanRoute);
router.use("/expense", expenseRoute);
router.use("/pf-policy", pfPolicyRoute);
router.use("/pf-account", pfAccountRoute);
router.use("/pf-contribution", pfContributionRoute);
router.use("/pf-withdrawal", pfWithdrawalRoute);
router.use("/attendance-policy", attendancePolicyRoute);
router.use("/attendance", attendanceRoute);
router.use("/leave-type", leaveTypeRoute);
router.use("/leave", leaveRoute);
router.use("/payroll-run", payrollRunRoute);
router.use("/special-payment-type", specialPaymentTypeRoute);
router.use("/special-payment", specialPaymentRoute);
router.use("/employee-request", employeeRequestRoute);
router.use("/holiday", holidayRoute);
router.use("/announcement", announcementRoute);
router.use("/recruitment/job", jobRoute);
router.use("/recruitment/candidate", candidateRoute);
router.use("/onboarding-template", onboardingTemplateRoute);
router.use("/onboarding", onboardingRoute);
router.use("/offboarding", offboardingRoute);
router.use("/finance/chart-of-account", chartOfAccountRoute);
router.use("/finance/journal", journalRoute);
router.use("/finance/ledger", ledgerRoute);
router.use("/finance/reports", reportsRoute);
router.use("/finance/bank-account", bankAccountRoute);
router.use("/finance/vendor-bill", vendorBillRoute);
router.use("/finance/customer-invoice", customerInvoiceRoute);
router.use("/finance/payment", paymentRoute);
router.use("/finance/income-entry", incomeEntryRoute);
router.use("/finance/business-expense", businessExpenseRoute);
router.use("/finance/vat-config", vatConfigRoute);
router.use("/finance/bank-statement-line", bankStatementLineRoute);
router.use("/finance/reconciliation-session", reconciliationSessionRoute);
router.use("/finance/budget", budgetRoute);
router.use("/asset-category", assetCategoryRoute);
router.use("/asset-request", assetRequestRoute);
router.use("/asset-audit", assetAuditRoute);
router.use("/asset", assetRoute);
router.use("/analytics/hr", hrAnalyticsRoute);
router.use("/analytics/inventory", inventoryAnalyticsRoute);
router.use("/analytics/sales", salesAnalyticsRoute);
router.use("/inventory/category", categoryRoute);
router.use("/inventory/product", productRoute);
router.use("/inventory/variant", variantRoute);
router.use("/inventory/production", productionRoute);
router.use("/inventory/stock-batch", stockBatchRoute);
router.use("/warehouse/warehouse", warehouseRoute);
router.use("/inventory/stock", stockRoute);
router.use("/warehouse/stock-transfer", stockTransferRoute);
router.use("/warehouse/stock-issue", stockIssueRoute);
router.use("/sales/customer", customerRoute);
router.use("/geo", geoRoute);
router.use("/sales/sale-invoice", saleInvoiceRoute);
router.use("/sales/quotation", quotationRoute);
router.use("/sales/credit-note", creditNoteRoute);
router.use("/purchase/supplier", supplierRoute);
router.use("/purchase/purchase-invoice", purchaseInvoiceRoute);
router.use("/purchase/debit-note", debitNoteRoute);
export default router;
